### ISSUE TITLE
K8s Conjur configuration documentation

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#2029] opened 2021-02-08 15:33 UTC
## User Story

**As a** Kubernetes operator 
**I want** detailed documentation for cluster and namespace configuration   
**So that** I can easily read Conjur’s Helm charts and/or incorporate it into my organization’s existing manifests. 

### Additional Details

* This needs to include both key/values names, as well the location of configuration in the cluster. 

## Implementation/Solution Notes

**Comment by izgeri** [comment] 2021-03-15 19:59
Closing as duplicate of cyberark/conjur-authn-k8s-client#235

**Closed by izgeri** 2021-03-15 19:59 UTC
Labels: Epic, kind/user-story, triage/duplicate
