### ISSUE TITLE
Related authenticators aren't fully validated against explicit `CONJUR_AUTHENTICATORS` list

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur#1220] opened 2019-11-13 12:22 UTC
If you define related authenticators they aren't validated at least in one case. For example, an enabled authenticator `authn-oidc/foo` will let `authn-oidc/bar` authenticator work even though the latter is not explicitly enabled.

AC:
- [x] Same-family authenticators aren't enabled as a whole group

**Comment by izgeri** [comment] 2020-03-10 19:29
@sgnn7 have you tried this since #1219 was merged to see if it's still an issue?

**Comment by sgnn7** [comment] 2020-03-10 19:44
No but I assume that this hasn't changed since being filed. Maybe @orenbm has done some fixes here since this issue was filed?

**Comment by izgeri** [comment] 2020-03-10 21:14
Oren asked about if this was resolved by the PR #1219 - this issue doesn't have details on reproducing, so I'm not sure how to reproduce exactly, but if you have a quick-ish way of doing it or can write up notes for someone else to take it on, it can help remove this high severity issue from this backlog.

**Comment by gsosin99** [comment] 2020-05-17 14:22
Couldn't reproduce this issue.

The steps that I tried to reproduce:

- Ran a conjur server with okta enabled and keycloak disabled 
- Loaded two polices of okta & keycloak
- Tried to authenticate with keycloak client and got the following error as expected:

DEBUG 2020/05/17 14:08:48 +0000 [pid=359] [origin=127.0.0.1] [request_id=17a9fd0b-d224-4e3e-b277-90c5be3de739] [tid=368] Authentication Error: #<Errors::Authentication::Security::AuthenticatorNotWhitelisted: CONJ00004E 'authn-oidc/keycloak' is not enabled>

Closing this ticket

**Closed by gsosin99** 2020-05-17 14:22 UTC
Labels: component/appliance, component/conjur, kind/bug, severity/high
