### ISSUE TITLE
Audit cukes should work without in-process server

### ISSUE THREAD

**Issue by dividedmind** [cyberark/conjur#579] opened 2018-06-21 10:58 UTC
Audit cuke tests as implemented in https://github.com/cyberark/conjur/commit/d98f09891d11b13e25a1a03d02efb5e84dfb2247 currently rely on using an in-process Conjur server.
Since scripts in `ci` use a server in a separate container, they're currently skipped by the build pipeline.

This should be addressed so that the full test suite is run automatically.

**Comment by jtuttle** [comment] 2020-04-16 15:49
Duplicate of #1486

**Closed by jtuttle** 2020-04-16 15:49 UTC
