### ISSUE TITLE
The "status page" doesn't load

### ISSUE THREAD

**Issue by brikelly** [cyberark/conjur#408] opened 2017-10-04 02:33 UTC
Conjur includes a simple "status page" that can be used to verify that it has been installed correctly and is reachable, etc. Currently that same page is not loading when Conjur is installed locally using the instructions from conjur.org.

**Comment by brikelly** [comment] 2017-10-04 02:34
For information on the status page feature: https://github.com/cyberark/conjur/issues/160

**Comment by ryanprior** [comment] 2017-10-06 17:03
Duplicate of #292, assigning @doodlesbykumbi to that issue.

**Closed by ryanprior** 2017-10-06 17:03 UTC
Labels: ready
