### ISSUE TITLE
docs describe authentication-container-name correctly

### ISSUE THREAD

**Issue by ismarc** [cyberark/conjur#676] opened 2018-08-13 14:35 UTC

**Comment by perrygold** [comment] 2019-01-31 18:09
This is a duplicate of issue #621, which is fixed for pre-5.2.4 . (it states that the container name must be a fixed value.)  when we release 5.2.4, there is another sentence that says with that release going forward, there are no restrictions on the container name.

**Closed** 2019-01-31 18:10 UTC
Labels: component/k8s, component/openshift, duplicate, kind/documentation, triage/needs-info
