### ISSUE TITLE
Search box for Group Memberships not working

### ISSUE THREAD

**Issue by typaulhus** [cyberark/conjur#704] opened 2018-08-27 15:20 UTC
![screenshot 2018-08-27 11 17 20](https://user-images.githubusercontent.com/123787/44668363-32d48f80-a9eb-11e8-80b6-90a5d4857e93.png)
When viewing a Group details page, the Permissions > Group Membership search box is not working.

**Comment by micahlee** [comment] 2018-08-30 13:03
Hey @typaulhus, is this a duplicate of https://github.com/conjurinc/conjur-ui/issues/200?

**Closed** 2018-08-30 21:42 UTC
Labels: bug, component/ui, ready
