### ISSUE TITLE
Helm chart for cluster Conjur configuration

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur#2027] opened 2021-02-08 15:28 UTC
## User Story

**As a** Kubernetes operator 
**I want** a Helm chart for creating Conjur resources and configuration common to all Conjur client workloads  
**So that** this configuration is centrally managed and does not need to be communicated to workload/app SREs. 

### Additional Details

* This must support Conjur deployed inside and outside the cluster. 
* Please practice README-driven UX, so that PO + team can review before implementation.  Docs can be found [here](https://docs.conjur.org/Latest/en/Content/Get%20Started/key_concepts/machine_identity.html).

## Implementation/Solution Notes

**Comment by izgeri** [comment] 2021-03-15 19:47
Duplicate of cyberark/conjur-authn-k8s-client#227

**Closed by izgeri** 2021-03-15 19:47 UTC
Labels: Epic, kind/user-story, triage/duplicate
