### ISSUE TITLE
absolute paths in a  nested policy aren't resolved correctly.

### ISSUE THREAD

**Issue by apotterri** [cyberark/conjur#600] opened 2018-07-03 18:10 UTC
This policy fails to load as the root policy in the `cucumber` account

```
- !user alice
- !user bob

- !policy
  id: dev
  owner: !user /alice
  body:
  - !policy
    id: db
    owner: !user /bob
```

`/alice` resolves correctly as `cucumber:user:alice`. However, `/bob` resolves to the role `cucumber:user:/bob@dev` rather than `cucumber:user:bob`.

**Comment by dividedmind** [comment] 2018-07-06 15:57
Actually the issue is with absolute !users in owners. Fixed with https://github.com/conjurinc/conjur-policy-parser/pull/11

**Comment by dividedmind** [comment] 2018-07-07 14:18
Note to self: update policy-parser dependency here after conjurinc/conjur-policy-parser#11 is merged.

**Closed** 2018-07-17 19:40 UTC
Labels: bug, review
